/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * PluginEndpoints
 * PluginEndpoints
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  PatchEmailOptinRequest,
  GetAdminPageInfoResponse,
  PostRegisterRequest,
  PostServicePoliciesRequest,
  GetPublicServicePoliciesResponse
} from './client.schemas'



  /**
 * Patch Email Optin.
 * @summary メールのオプトインを更新する
 */
export const patchAdminEmailOptin = <TData = AxiosResponse<void>>(
    patchEmailOptinRequest: PatchEmailOptinRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/admin/email-optin`,
      patchEmailOptinRequest,options
    );
  }

/**
 * Get Admin Page Info.
 * @summary 管理者ページ情報取得
 */
export const getAdminPageinfo = <TData = AxiosResponse<GetAdminPageInfoResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/admin/pageinfo`,options
    );
  }

/**
 * Post Service Policies.
 * @summary 管理者ページ情報を登録
 */
export const postAdminRegister = <TData = AxiosResponse<void>>(
    postRegisterRequest: PostRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/admin/register`,
      postRegisterRequest,options
    );
  }

/**
 * Post Service Policies.
 * @summary サービスとポリシー更新
 */
export const postAdminServicePolicies = <TData = AxiosResponse<void>>(
    postServicePoliciesRequest: PostServicePoliciesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/admin/service-policies`,
      postServicePoliciesRequest,options
    );
  }

/**
 * Get Service Policies for shortcode.
 * @summary サービスとポリシー取得
 */
export const getPublicServicePolicies = <TData = AxiosResponse<GetPublicServicePoliciesResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/public/service-policies`,options
    );
  }

export type PatchAdminEmailOptinResult = AxiosResponse<void>
export type GetAdminPageinfoResult = AxiosResponse<GetAdminPageInfoResponse>
export type PostAdminRegisterResult = AxiosResponse<void>
export type PostAdminServicePoliciesResult = AxiosResponse<void>
export type GetPublicServicePoliciesResult = AxiosResponse<GetPublicServicePoliciesResponse>
