/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * 電気通信事業法プラグインのPHPバックエンド
 * 電気通信事業法プラグインのPHPバックエンド
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  GetAdminPageInfoResponse,
  PostServicePoliciesRequest,
  GetPublicServicePoliciesResponse
} from './client.schemas'



  /**
 * Get Admin Page Info.
 * @summary 管理者ページ情報取得
 */
export const getAdminPageinfo = <TData = AxiosResponse<GetAdminPageInfoResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/admin/pageinfo`,options
    );
  }

/**
 * Post Service Policies.
 * @summary サービスとポリシー更新
 */
export const postAdminServicePolicies = <TData = AxiosResponse<void>>(
    postServicePoliciesRequest: PostServicePoliciesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/admin/service-policies`,
      postServicePoliciesRequest,options
    );
  }

/**
 * Get Service Policies for shortcode.
 * @summary サービスとポリシー取得
 */
export const getPublicServicePolicies = <TData = AxiosResponse<GetPublicServicePoliciesResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/public/service-policies`,options
    );
  }

export type GetAdminPageinfoResult = AxiosResponse<GetAdminPageInfoResponse>
export type PostAdminServicePoliciesResult = AxiosResponse<void>
export type GetPublicServicePoliciesResult = AxiosResponse<GetPublicServicePoliciesResponse>
