name: Deploy

on:
  push:
    branches:
      - "release"

jobs:
  phpunit:
    name: PHPUnit on ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Composer Install
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Unit Test
        run: composer run-script phpunit

      - name: Slackに結果を通知する
        id: slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  vitest:
    name: Vitest on (${{ matrix.node-versions }}
    needs: phpunit
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-versions: ['17.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Vitest
        working-directory: ./frontend
        run: npm run test

  deploy:
    name: Build and Deploy
    needs: vitest
    runs-on: ubuntu-latest

    steps:
      - name: Slackに結果を通知する
        id: slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()