name: plugin phpunit test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  phpunit:
    name: PHPUnit on ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Composer Install
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Unit Test
        run: composer run-script phpunit

  vitest:
    name: Vitest on node js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-versions: ['17.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Vitest
        working-directory: ./frontend
        run: npm run test
